### ISSUE TITLE
Feat: Automatic Release Change Log Workflow for Project 

### ISSUE THREAD

**Issue by Nishitbaria** [avinashkranjan/Friday#360]
### Describe the feature

Currently, our project lacks an automated release change log generation process, making it cumbersome for contributors and users to track changes and updates between releases. This feature is crucial for enhancing transparency, improving communication, and promoting a more streamlined development process. To address this, we propose implementing an automatic release change log workflow that generates a detailed and user-friendly log with each release.

### Add ScreenShots

```
name: Automated Change Log Generation

on:
  release:
    types: [created]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Change Log
      run: |
        # Add your change log generation script/tool here
        # For example:
        # npx conventional-changelog -p angular -i CHANGELOG.md -s

    - name: Commit Change Log
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add CHANGELOG.md
        git commit -m "Automated change log update for release ${{ github.ref }}"
        git push

```
